### ISSUE TITLE
Tanzania: Assign to Researcher, Researcher not showing up in dropdown

### ISSUE THREAD

**Issue by giorgiacek** [NRGI/mga-assessment-tool#19]
AC Howards wants to assign the Tanzania assessment to the researcher Christiana Pangalos, but when trying to assign it, christiana pangalos does not show up in the list of researchers.

**Comment by byndcivilization** [comment]
Bug in assignment function. Not writing researcher id to the assessment record.

**Comment by byndcivilization** [comment]
Cant recreate so closing ticket for now
