### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/mga-assessment-tool#8]
Allow supervisors to navigate across full questionnaire,
No need to fill full desk questionaire to access interview questions  (as unlikely they will be ready on time)

**Comment by byndcivilization** [comment]
Does this mean that there isn't really a control flow then. In other words, theres not really a formal handoff to country teams from desk research team?

**Comment by davidmihalyi** [comment]
That was the plan but looks much less likely in Ghana / Moz where same people will do both under again a squashed timeline

Sent from my iPhone

On 14 Jul 2015, at 20:56, Chris Perry <notifications@github.com<mailto:notifications@github.com>> wrote:

Does this mean that there isn't really a control flow then. In other words, theres not really a formal handoff to country teams from desk research team?

##
